// AUTH TYPE
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
// MESSAGE TYPE
export const GET_USER_MESSAGE = 'GET_USER_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MORE_MESSAGES = 'GET_MORE_MESSAGES'
export const UPDATE_LAST_MESSAGE = 'UPDATE_LAST_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION'
//GALLERY TYPE
export const GET_IMAGE_GALLERY = 'GET_IMAGE_GALLERY'
export const GET_VIDEO_GALLERY = 'GET_VIDEO_GALLERY'
export const GET_FILE_GALLERY = 'GET_FILE_GALLERY'
export const GET_ACTIVE_IMAGE = 'GET_ACTIVE_IMAGE'
export const REMOVE_ACTIVE_IMAGE = 'REMOVE_ACTIVE_IMAGE'
//SOCKET
export const CREATE_SOCKET_INSTANCE = 'CREATE_SOCKET_INSTANCE'
export const ONLINE_USER = 'ONLINE_USER'
export const ADD_USER_ONLINE = 'ADD_USER_ONLINE'
export const REMOVE_ONLINE_USER = 'REMOVE_ONLINE_USER'