// AUTH TYPE
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
// MESSAGE TYPE
export const GET_USER_MESSAGE = 'GET_USER_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const UPDATE_CONVERSATIONS = 'UPDATE_CONVERSATIONS'
export const GET_MESSAGES = 'GET_MESSAGES'